server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false # TODO: Added for debug purpose and should be disabled

# Application configurations
# JWT configurations
jwt:
  secret: SecretJwtString
  access-token-expiration-seconds: 900 # 15 minutes
  refresh-token-expiration-seconds: 604800 # 1 week
