server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop

# Application configurations
# JWT configurations
jwt:
  secret: SecretJwtString
  access-token-expiration-seconds: 90 # 15 minutes (TODO: For test purpose decreased and should reverted).
  refresh-token-expiration-seconds: 604800 # 1 week
