server:
  port: 8080
  error:
    # Show error message in server error: https://stackoverflow.com/a/62586031/
    include-message: always
    include-exception: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
  sql:
    init:
      platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false # TODO: Added for debug purpose and should be disabled
    properties:
      hibernate:
        format_sql: false # TODO: Added for debug purpose and should be disabled

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB

  # To redirect the exception to our advice (ResponseEntityExceptionHandler) instead of DefaultHandlerExceptionResolver
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

# Application configurations

# JWT configurations
jwt:
  secret: SecretJwtString
  # TODO: Decrease it to 900 (15 minutes) after ready for deployment
  access-token-expiration-seconds: 3600 # 15 minutes
  refresh-token-expiration-seconds: 604800 # 1 week

# Local data file paths
local-paths:
  root-directory: data
  problem-events: problemEvents