server:
  port: 8080
  error:
    include-message: always # Show error message in server error: https://stackoverflow.com/a/62586031/3739748
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false # TODO: Added for debug purpose and should be disabled

# Application configurations
# JWT configurations
jwt:
  secret: SecretJwtString
  # TODO: Decrease it to 900 (15 minutes) after ready for deployment
  access-token-expiration-seconds: 3600 # 15 minutes
  refresh-token-expiration-seconds: 604800 # 1 week
