server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb

# Application configurations
# JWT configurations
jwt:
  secret: SecretJwtString
  expiration-seconds: 86400 # 1 day
